spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///springboot
    username: root
    password: 310013


#开启Mp的日志（输出到控制台）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id #设置id生成策略
      table-prefix: t_ #设置表名前缀
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

main:
  banner-mode: off
